services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=tripdetails'
      - 'POSTGRES_PASSWORD=pass'
      - 'POSTGRES_USER=user'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432'
